all:
  children:
    servers:
      hosts:
        tunenumbers:
          ansible_host: "{{ lookup('env', 'SERVER_IP') | default('203.0.113.1', true) }}"
          ansible_user: "{{ lookup('env', 'SERVER_USER') | default('deploy', true) }}"
