apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/postgresql
    type: DirectoryOrCreate
  claimRef:
    namespace: tunenumbers
    name: postgresql-pvc
