apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
  namespace: gitea
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  volumeName: gitea-pv
  resources:
    requests:
      storage: 5Gi
